# Generated by Django 5.2.7 on 2025-11-05 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
                ('cost_price', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='RawProductRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_row', models.JSONField()),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('cleaning', 'Cleaning'), ('cleaned', 'Cleaned'), ('error', 'Error')], default='raw', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_products', to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='RawSalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_row', models.JSONField()),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('cleaning', 'Cleaning'), ('cleaned', 'Cleaned'), ('error', 'Error')], default='raw', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_sales', to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('channel', models.CharField(default='offline', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_data.product')),
            ],
        ),
    ]
